name: Monitor Exchange Rates

on:
  schedule:
    - cron: "*/5 * * * *" # Run every 5 minutes
  workflow_dispatch: # Allow manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitoring script
        env:
          EMAIL_SMTP_SERVER: smtp.qiye.aliyun.com
          EMAIL_SMTP_PORT: 465
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: python exchange_monitor.py
